In [3]:
import numpy as np
import pandas as pd 
from sklearn import cross_validation
from sklearn.cross_validation import KFold
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestClassifier 
from sklearn.cross_validation import cross_val_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_recall_fscore_support
%matplotlib inline
import matplotlib.pyplot as plt
import scipy.stats

In [4]:
import sys
import lmdb
import h5py
caffe_root = '/work/sagarj/caffe-rc5/'  # this file should be run from {caffe_root}/examples (otherwise change this line)
sys.path.insert(0, caffe_root + 'python')
from collections import defaultdict
import caffe


In [31]:
model_root = "/work/sagarj/Work/BellLabs/caffe_models/caffe_model_1/"
# net_weights='caffe_beauty_augmented/caffe_model_beauty_augmented_iter_10000.caffemodel'
net_weights='caffe_model_beauty_4_votes/caffe_model_1_iter_24732.caffemodel'
net_definition='caffenet_deploy_1.prototxt'

test_lmdb_path = '../Data/validation_lmdb_beauty_augmented' # Test LMDB database path
mean_file_binaryproto = '../Data/cityAugmentedMean.binaryproto' # Mean image file


In [32]:
caffe.set_mode_gpu()
model_def = model_root+net_definition
model_weights = model_root + net_weights

In [34]:
net = caffe.Net(model_def,      # defines the structure of the model
                model_weights,  # contains the trained weights
                caffe.TEST)     # use test mode (e.g., don't perform dropout)


In [35]:
np.asarray(net.blobs['fc8'].data)

array([[ 0.,  0.]], dtype=float32)

In [36]:
# Extract mean from the mean image file
mean_blobproto_new = caffe.proto.caffe_pb2.BlobProto()
f = open(mean_file_binaryproto, 'rb')
mean_blobproto_new.ParseFromString(f.read())
mean_image = caffe.io.blobproto_to_array(mean_blobproto_new)
f.close()

In [37]:
count = 0
correct = 0
labels = [] # (real,pred) -> int
preds = []
# labels_set = set()

lmdb_env = lmdb.open(test_lmdb_path)
lmdb_txn = lmdb_env.begin()
lmdb_cursor = lmdb_txn.cursor()

for key, value in lmdb_cursor:
    datum = caffe.proto.caffe_pb2.Datum()
    datum.ParseFromString(value)
    label = datum.label
    labels.append(label)
    image = caffe.io.datum_to_array(datum)
    image = image.astype(np.uint8)
    out = net.forward_all(data=np.asarray([image]) - mean_image).copy()

    plabel = out['prob']
    preds.append(plabel)
    count += 1

In [38]:
preds[3]

array([[ 0.62243974,  0.37756029]], dtype=float32)

In [39]:
pred_label = [np.argmax(i) for i in preds ]

In [40]:
pred_label[2] , labels[2]

(0, 0)

In [41]:
error_RF = mean_squared_error(labels, pred_label)

accuracy = np.mean(labels == pred_label)

precision , recall , fscore , _ = precision_recall_fscore_support(labels, pred_label)


print ( precision , recall , fscore)

(array([ 0.77590361,  0.52041574]), array([ 0.66597725,  0.65330848]), array([ 0.71675014,  0.57933884]))


In [42]:
accuracy

0.0